{
 "title": "Minecraft Singleplayer",
 "description": "Minecraft Prometheus Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(minecraft_dataversion_info{job=~\"$job\"},  instance)"
    }
   },
   {
    "name": "world",
    "label": "World",
    "query": {
     "query": "label_values(minecraft_dataversion_info{job=~\"$job\", instance=~\"$instance\"},  world)"
    }
   },
   {
    "name": "player",
    "label": "Player",
    "query": {
     "query": "label_values(minecraft_dataversion_info{job=~\"$job\", instance=~\"$instance\", world=~\"$world\"},  player)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Played",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"minecraft_custom_minecraft_play_time_total\", job=\"$job\", instance=\"$instance\", world=\"$world\", player=\"$player\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Distance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Mob Kills",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"minecraft_custom_minecraft_mob_kills_total\", job=\"$job\", instance=\"$instance\", world=\"$world\", player=\"$player\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Times Slept in a Bed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"minecraft_custom_minecraft_sleep_in_bed_total\", job=\"$job\", instance=\"$instance\", world=\"$world\", player=\"$player\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jumps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"minecraft_custom_minecraft_jump_total\", job=\"$job\", instance=\"$instance\", world=\"$world\", player=\"$player\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Distances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Distances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{__name__=~\".*one_cm.*\", job=\"$job\", instance=\"$instance\", world=\"$world\", player=\"$player\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Items", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  { "title": "Mobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Interactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{__name__=~\"(.*interact.*)|(.*open_chest_total.*)\", job=\"$job\", instance=\"$instance\", world=\"$world\", player=\"$player\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}